#!/usr/bin/expect
set timeout -1
set arg1 [lindex $argv 0]
spawn ssh -N -L 0.0.0.0:5511:10.254.255.100:22 $arg1
match_max 100000
expect {
	"*?assword:*" {
		send -- "\x31\x31\x31\x31\x31\x31\r"
		exp_continue
	}
	"*?(yes/no)*" {
		send -- "yes\r"
		exp_continue
	}
	"*?Connection refused*" {
		exp_continue
	}
	"*?Permission denied*" {
		exp_continue
	}
	"*?auth failed*" {
		exp_continue
	}
	"*?Unknown module*" {
		exp_continue
	}
}
exit
